language: c
script: make && make fs.img
language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: hIuUyj8mZRRCrouyt2fuGGQYUpPFzuRXsSFPiX9UUU2FsacPdBiNC5TN00G3Y4KMBFESKU6w8SztV/6TZGYdeAoalQ8kIMIOMqqkz2Fzqc9F31X54fixrz7IJZWMv4TLM1y5m53QnwTgdw/QA0rK+Gbv4ekUSlnX/mVjUUctsEG7WeorF0ege8vpUCxkDpdOMHexlZN5Ok/F4bc4HOkAiovckQ3K5c4/YHkPgVabTCHg24ljoJdT5JdXoTP5UZa1lo/jHVqbcCbcjRyuWgkNOfsVTjRQmIx0PjPTWIs+hnKsnbTkvIwo5ejclzt3zkCnzET+ZsyUAEbEUV0IJPzFmfESmu5fLjEwB5A6WzG6qfVziZNXd6qc0PgXV7VBK+PTqArpxdZm/T/BIgC2BE/bPfcfbYeEv4HMAJShIcqpMIFOG6mG05oa6BYoPDdiD4nyeAL4gwaXVaHQXtKBAKNQ0IcD+aCtrJ3twaHXP/xPoRputKZnx7l6hXCOH9daoSmrBZrJZ1XJX/B9FnbVckbzj277dQ/JX7Ag4FtTvno94v1R3oDodxX9AuesjfopDEndhcgPeG/uxsikaxcJXUrNQ7YywH9bzkecsAj76I5kGiMMvITN+SIZ2Vmx7QBnGcbuUEObGEUuGgXzIUMpZm2FYT1vZz+ySux0ZMroQQodaH8=
  file: 
    - fs.img
    - xv6.img
  skip_cleanup: true
  on:
    repo: mrMustacho/xv6-public
    branch: original
  tags: true
